[tool.poetry]
name = "demo-server"
version = "0.1.0"
description = ""
authors = ["David Neugebauer <david.neugebauer@posteo.de>"]

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^1.1.2"
peewee = "^3.13.2"
APScheduler = "^3.6.3"

[tool.poetry.dev-dependencies]
